                              Random Forest

In [14]:
import pandas as pd

In [15]:
ams=pd.read_csv(r'Desktop/test.csv')

In [16]:
ams.head()

accommodates  bathrooms  bedrooms  calculated_host_listings_count  \
0             3        1.0         1                               1   
1             2        1.0         1                               1   
2             5        2.0         5                              11   
3             4        1.0         2                               1   
4             2        1.0         1                               1   

   guests_included  host_listings_count   latitude  longitude  minimum_nights  \
0                1                    1  52.339005   4.944442               5   
1                1                    1  52.374981   4.890104               3   
2                2                   15  52.401826   4.914041               6   
3                1                    1  52.350448   4.798421               2   
4                1                    1  52.361044   4.943895               5   

   number_of_reviews  d_centre  instant_bookable_f  instant_bookable_t  \
0                  7  5.410324                   1                   0   
1                  9  0.786783                   1                   0   
2                  4  2.703668                   1                   0   
3                  0  7.561760                   1                   0   
4                  3  3.628639                   1                   0   

   room_type_Entire home/apt  room_type_Private room  room_type_Shared room  
0                          1                       0                      0  
1                          1                       0                      0  
2                          1                       0                      0  
3                          1                       0                      0  
4                          1                       0                      0

In [17]:
ams.shape

(4500, 16)

In [18]:
ams.columns

Index(['accommodates', 'bathrooms', 'bedrooms',
       'calculated_host_listings_count', 'guests_included',
       'host_listings_count', 'latitude', 'longitude', 'minimum_nights',
       'number_of_reviews', 'd_centre', 'instant_bookable_f',
       'instant_bookable_t', 'room_type_Entire home/apt',
       'room_type_Private room', 'room_type_Shared room'],
      dtype='object')

In [19]:
ams.isnull().sum()

accommodates                      0
bathrooms                         0
bedrooms                          0
calculated_host_listings_count    0
guests_included                   0
host_listings_count               0
latitude                          0
longitude                         0
minimum_nights                    0
number_of_reviews                 0
d_centre                          0
instant_bookable_f                0
instant_bookable_t                0
room_type_Entire home/apt         0
room_type_Private room            0
room_type_Shared room             0
dtype: int64

In [20]:
x=ams.iloc[:,1:16]
y=ams.iloc[:,0]
x


bathrooms  bedrooms  calculated_host_listings_count  guests_included  \
0           1.0         1                               1                1   
1           1.0         1                               1                1   
2           2.0         5                              11                2   
3           1.0         2                               1                1   
4           1.0         1                               1                1   
5           1.0         2                               2                1   
6           1.5         1                               1                1   
7           1.0         0                               1                1   
8           1.0         2                               1                1   
9           1.0         3                               1                1   
10          2.0         2                               2                4   
11          1.0         1                               1                1   
12          1.0         1                               2                1   
13          1.0         2                               1                2   
14          1.0         2                               1                4   
15          1.0         1                               3                1   
16          1.0         1                              38                1   
17          1.0         1                              42                1   
18          1.0         2                               1                2   
19          1.0         1                               1                1   
20          1.0         1                               1                1   
21          1.0         2                               2                1   
22          2.0         2                               3                4   
23          1.0         1                               1                2   
24          1.0         1                               1                2   
25          1.0         1                               1                1   
26          1.0         3                               1                4   
27          1.0         1                               1                1   
28          1.0         1                               1                1   
29          1.0         2                               1                4   
...         ...       ...                             ...              ...   
4470        1.0         5                               1                1   
4471        1.0         1                               1                1   
4472        1.0         1                              13                1   
4473        1.0         1                               1                1   
4474        1.0         1                               1                1   
4475        1.0         1                               1                2   
4476        1.0         1                               1                1   
4477        1.0         1                               1                1   
4478        1.5         3                               1                1   
4479        1.0         1                               1                1   
4480        1.0         1                               1                1   
4481        1.0         1                               1                1   
4482        1.0         1                               1                2   
4483        1.0         2                               1                2   
4484        1.0         2                               1                1   
4485        1.0         0                               1                1   
4486        1.0         1                               1                1   
4487        1.0         1                               1                1   
4488        1.0         1                               1                1   
4489        1.5         2   

In [21]:
y

0       3
1       2
2       5
3       4
4       2
5       2
6       2
7       2
8       4
9       4
10      4
11      2
12      2
13      4
14      4
15      2
16      3
17      2
18      3
19      2
20      2
21      3
22      4
23      2
24      2
25      2
26      6
27      2
28      2
29      5
       ..
4470    4
4471    3
4472    2
4473    2
4474    2
4475    2
4476    2
4477    2
4478    4
4479    2
4480    2
4481    2
4482    2
4483    2
4484    3
4485    2
4486    2
4487    2
4488    1
4489    5
4490    2
4491    1
4492    6
4493    2
4494    2
4495    2
4496    4
4497    2
4498    3
4499    2
Name: accommodates, Length: 4500, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [23]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

C:\Users\naresh\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\naresh\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\naresh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


In [24]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

In [26]:
from sklearn import metrics
import numpy as np
metrics.mean_absolute_error(y_test,y_pred)
metrics.mean_squared_error(y_test,y_pred)
np.sqrt(metrics.mean_squared_error(y_test,y_pred))

0.7779364917428576

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import accuracy_score 
confusion_matrix(y_test,y_pred)

array([[  0,  28,   0,   0,   0,   0,   0,   0,   0],
       [  0, 722,   7,  40,   0,   0,   0,   0,   0],
       [  0,  60,   2,  53,   0,   0,   0,   0,   0],
       [  0,  62,   3, 301,   2,   3,   0,   0,   0],
       [  0,   2,   0,  25,   0,   4,   0,   0,   0],
       [  0,   0,   0,  27,   0,   3,   0,   0,   0],
       [  0,   0,   0,   1,   0,   0,   0,   0,   0],
       [  0,   0,   0,   4,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   1,   0,   0,   0]], dtype=int64)

In [29]:
np.mean(y_test==y_pred)

0.7614814814814815

                             KNN Classification 

In [30]:
x=ams.iloc[:,1:16]
x.head(2)

bathrooms  bedrooms  calculated_host_listings_count  guests_included  \
0        1.0         1                               1                1   
1        1.0         1                               1                1   

   host_listings_count   latitude  longitude  minimum_nights  \
0                    1  52.339005   4.944442               5   
1                    1  52.374981   4.890104               3   

   number_of_reviews  d_centre  instant_bookable_f  instant_bookable_t  \
0                  7  5.410324                   1                   0   
1                  9  0.786783                   1                   0   

   room_type_Entire home/apt  room_type_Private room  room_type_Shared room  
0                          1                       0                      0  
1                          1                       0                      0

In [31]:
from sklearn.preprocessing import scale

In [32]:
x=scale(x)
x

C:\Users\naresh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  """Entry point for launching an IPython kernel.


array([[-0.35780738, -0.48260407, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351],
       [-0.35780738, -0.48260407, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351],
       [ 2.98966293,  4.35957725,  0.91691388, ...,  0.53486609,
        -0.52626799, -0.07474351],
       ...,
       [-0.35780738, -0.48260407, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351],
       [-0.35780738, -0.48260407, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351],
       [-0.35780738, -0.48260407, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351]])

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [34]:
x_test

array([[-0.35780738, -0.48260407, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351],
       [-0.35780738,  0.72794126, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351],
       [-0.35780738,  0.72794126, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351],
       ...,
       [-0.35780738, -0.48260407, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351],
       [-0.35780738, -0.48260407, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351],
       [-0.35780738, -0.48260407, -0.22016344, ...,  0.53486609,
        -0.52626799, -0.07474351]])

In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [37]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=30)
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=30, p=2,
           weights='uniform')

In [38]:
y_pred=classifier.predict(x_test)

In [39]:
import numpy as np

In [40]:
np.mean(y_pred==y_test)

0.7481481481481481

In [ ]:
from sklearn.metrics import confusion_matrix

y_test = [1, 1, 0, 0]
y_pred = [1, 0, 1, 0]   

tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print(tn, fp, fn, tp) 